version: '3.7'

#Agregado: Se define una red que compartirán los servicios api y mock
networks:
  atc-network:

services:
  api:
    image: atc-challenge:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      ATC_BASE_URL: http://mock:4000
    #Agregado: Conectamos la API a la red y definimos la dependencia
    networks:
      - atc-network
    depends_on:
      mock: 
        condition: service_healthy
      redis:
        condition: service_healthy

  mock:
    # image: atc-challenge:dev
    build: ./mock
    command: node server.js
    volumes:
      - ./mock:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 60
      EVENT_PUBLISHER_URL: http://api:3000/events
    # --- Agregado: Conectamos el mock a la misma red ---
    networks:
      - atc-network
    # --- AÑADIDO: La prueba de salud ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/zones"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    networks:
      - atc-network
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5